var arrAll=[
    {name:"北京",
     sub:[
        {name:"请选择",sub:[]},
        {
            name:"北京",
            sub:[{name:"请选择"},{name:"阿坝"},{name:"阿拉善"},{name:"阿里"},{name:"安康"},{name:"安庆"},{name:"鞍山"},{name:"安顺"},{name:"安阳"}]      
        }]
    },
    {name:"广东",
     sub:[
        {name:"请选择",sub:[]},
        {
            name:"广州",
            sub:[{name:"请选择"},{name:"阿坝1"},{name:"阿拉善1"},{name:"阿里1"},{name:"安康1"},{name:"安庆1"},{name:"鞍山1"},{name:"安顺1"},{name:"安阳1"}]      
        },
        {
            name:"深圳",
            sub:[{name:"请选择"},{name:"阿坝2"},{name:"阿拉善2"},{name:"阿里2"},{name:"安康2"},{name:"安庆2"},{name:"鞍山2"},{name:"安顺2"},{name:"安阳2"}]      
        },
        {
            name:"珠海",
            sub:[{name:"请选择"},{name:"阿坝3"},{name:"阿拉善3"},{name:"阿里3"},{name:"安康3"},{name:"安庆3"},{name:"鞍山3"},{name:"安顺3"},{name:"安阳3"}]      
        },
    ]
    },
    {name:"上海",
     sub:[
        {name:"请选择",sub:[]},
        {
            name:"广州2",
            sub:[{name:"请选择"},{name:"阿坝4"},{name:"阿拉善4"},{name:"阿里4"},{name:"安康4"},{name:"安庆4"},{name:"鞍山4"},{name:"安顺4"},{name:"安阳4"}]      
        },
        {
            name:"深圳2",
            sub:[{name:"请选择"},{name:"阿坝5"},{name:"阿拉善5"},{name:"阿里5"},{name:"安康5"},{name:"安庆5"},{name:"鞍山5"},{name:"安顺5"},{name:"安阳5"}]      
        },
        {
            name:"珠海2",
            sub:[{name:"请选择"},{name:"阿坝6"},{name:"阿拉善6"},{name:"阿里6"},{name:"安康6"},{name:"安庆6"},{name:"鞍山6"},{name:"安顺6"},{name:"安阳6"}]      
        },
    ]
   },

]